url: https://y7kim.github.io
baseurl: 

# Site settings
title: Hassan Mir
email: hassanmir92@gmail.com
description: "Hi my name is Hassan and I am currently a WDI student at General assembly London on my way to becoming a junior web developer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/hassanmir92
  - title: linkedin
    url: http://uk.linkedin.com/in/hassanmir92
  - title: twitter
    url: http://twitter.com/Hassanmir92

# Build settings
markdown: kramdown
permalink: pretty