# Site settings
title: Hassan Mir | Web Developer
description: "Web Development Immersive Student at General Assembly"
url: ""
author:
  name: "Hassan Mir"
  url: ""

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
